# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e6267ea115919bd05beda39851f2f5a61670dd91c4609bb547d7440c32310244d81e3f22109623c8df6e1779ab33872be3e83ea4da8f1742a859fb5c9bd7612

test:
  secret_key_base: 2eeae2e8935a6111e07827ab574a2fb562f3f3ef1373e15c7d3c8b174364bd9da3c5286cb591e9989888a4ec1c69a9b64b9ab92791e5b5495c18a17727eb8454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
